apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-streamer
  namespace: streamer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-streamer
  template:
    metadata:
      labels:
        app: simple-streamer
    spec:
      containers:
      - name: simple-streamer
        image: 635014547592.dkr.ecr.us-east-1.amazonaws.com/streamer:839d541d75e0be11729d338b912fa2f5dcfa4f02
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"    # 최소 0.2 코어 보장
            memory: "256Mi" # 최소 256MB 메모리 보장
          limits:
            cpu: "500m"    # 최대 0.5 코어까지만 사용
            memory: "1Gi" # 최대 1GB 메모리 사용
        env:
        - name: DB_HOST
          value: "hybrid-prod-db-2.c8bacacucmpz.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "videodb"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          value: "12345678"  # TODO: 실제 DB 비밀번호로 변경
        - name: S3_BUCKET
          value: "prod-video-bucket-idac-2026"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key-aws

---
apiVersion: v1
kind: Service
metadata:
  name: simple-streamer-svc
  namespace: streamer
spec:
  type: ClusterIP
  selector:
    app: simple-streamer
  ports:
    - port: 80
      targetPort: 8080