apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-streamer-ingress
  namespace: streamer
  annotations:
    # 헬스 체크나 바디 크기 제한 해제 (동영상 업로드 위해 필수)
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx  # 1단계에서 설치한 nginx controller를 사용
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-streamer-svc
            port:
              number: 80